export const SESSION_ERRORS = {
	MAGIC_LINK_GENERATED_RECENTLY: 'MAGIC_LINK_GENERATED_RECENTLY',
	INVALID_MAGIC_TOKEN: 'INVALID_MAGIC_TOKEN',
	MISSING_MAGIC_IDENTIFIER: 'MISSING_MAGIC_IDENTIFIER',
	UNABLE_TO_SEND_EMAIL: 'MISSING_MAGIC_IDENTIFIER',
	SIGNED_IN_ONLY: 'SIGNED_IN_ONLY',
	SIGNED_OUT_ONLY: 'SIGNED_OUT_ONLY',
} as const;
