name: CI/CD

on:
  push:
    branches: [main]

jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Use Node.js 16
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: '16'

      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Lint code
        run: pnpm lint --max-warnings 0

      - name: Typecheck
        run: pnpm vue-tsc

      - name: Deploy
        run: pnpm --package=@railway/cli dlx railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
